[['X' '1' '2' '4']
 ['3' '4' '1' '3']
 ['6' '0' '2' '3']]
[[1, 0]]
[[2, 0]]
[[0, 1]]
[['X' 'R' '2' '4']
 ['I' '4' 'S' '3']
 ['C' '0' '2' '3']]
('total Points: ', [[-20, 'badddce6']])


python main.py urban\ 2.txt GA
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    main(sys.argv[1:])
  File "main.py", line 40, in main
    gent.solve()
  File "/home/ashay/AI_assignments/assignment_1/UrbanPlanning/genetic_algo.py", line 43, in solve
    self.fillLocations(unique_id, i)
  File "/home/ashay/AI_assignments/assignment_1/UrbanPlanning/genetic_algo.py", line 53, in fillLocations
    self.getRowCol(loc_i, icr)
  File "/home/ashay/AI_assignments/assignment_1/UrbanPlanning/genetic_algo.py", line 75, in getRowCol
    if self.locations_s[i][0] == row and self.locations_s[i][1] == col:
IndexError: index 1 is out of bounds for axis 0 with size 1